/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Password Reset */
        post: operations["request_password_reset_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password Reset */
        post: operations["confirm_password_reset_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_password_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_v1_users_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Log
         * @description Newest first, optionally narrowed to one match.
         */
        get: operations["list_audit_log_api_v1_admin_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Link User Player
         * @description Point an account at the roster player whose stats are its own.
         *
         *     Personal invitations cover accounts made from here on; this covers the ones
         *     that already exist, and the times a link was made against the wrong player.
         *     Passing null unlinks.
         */
        patch: operations["link_user_player_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/registration-invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invites */
        get: operations["list_invites_api_v1_admin_registration_invites_get"];
        put?: never;
        /** Create Invite */
        post: operations["create_invite_api_v1_admin_registration_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/registration-invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_api_v1_admin_registration_invites__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_v1_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_api_v1_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Team */
        delete: operations["delete_team_api_v1_teams__team_id__delete"];
        options?: never;
        head?: never;
        /** Update Team */
        patch: operations["update_team_api_v1_teams__team_id__patch"];
        trace?: never;
    };
    "/api/v1/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Competitions */
        get: operations["list_competitions_api_v1_competitions_get"];
        put?: never;
        /** Create Competition */
        post: operations["create_competition_api_v1_competitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/competitions/{competition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Competition */
        delete: operations["delete_competition_api_v1_competitions__competition_id__delete"];
        options?: never;
        head?: never;
        /** Update Competition */
        patch: operations["update_competition_api_v1_competitions__competition_id__patch"];
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_api_v1_players_get"];
        put?: never;
        /** Create Player */
        post: operations["create_player_api_v1_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Player */
        delete: operations["delete_player_api_v1_players__player_id__delete"];
        options?: never;
        head?: never;
        /** Update Player */
        patch: operations["update_player_api_v1_players__player_id__patch"];
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_api_v1_matches_get"];
        put?: never;
        /** Create Match */
        post: operations["create_match_api_v1_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match */
        get: operations["get_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        /** Delete Match */
        delete: operations["delete_match_api_v1_matches__match_id__delete"];
        options?: never;
        head?: never;
        /** Update Match */
        patch: operations["update_match_api_v1_matches__match_id__patch"];
        trace?: never;
    };
    "/api/v1/matches/{match_id}/phase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Match Phase */
        post: operations["update_match_phase_api_v1_matches__match_id__phase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Result
         * @description The whole scoring surface for a match between two opponent clubs.
         *
         *     Everywhere else a scoreline is derived from the timeline and never written
         *     by hand, because the timeline is the record. Here there is no timeline to
         *     derive it from, so the score is the record, and this is the only route that
         *     may set it. Kept off PATCH deliberately: PATCH takes a whole match, and
         *     widening it would let a stale client roll a corrected score back.
         *
         *     It goes straight to finished without asking the clock, since scheduled to
         *     finished is a transition the phase machine has no reason to allow. Calling
         *     it again on a finished match is how a wrong score is corrected.
         */
        post: operations["record_result_api_v1_matches__match_id__result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/man-of-the-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Man Of The Match */
        post: operations["set_man_of_the_match_api_v1_matches__match_id__man_of_the_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_matches__match_id__events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_api_v1_matches__match_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Event */
        delete: operations["delete_event_api_v1_matches__match_id__events__event_id__delete"];
        options?: never;
        head?: never;
        /** Edit Event */
        patch: operations["edit_event_api_v1_matches__match_id__events__event_id__patch"];
        trace?: never;
    };
    "/api/v1/matches/{match_id}/lineup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lineup */
        get: operations["get_lineup_api_v1_matches__match_id__lineup_get"];
        /** Replace Lineup */
        put: operations["replace_lineup_api_v1_matches__match_id__lineup_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/player-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Stats */
        get: operations["get_player_stats_api_v1_matches__match_id__player_stats_get"];
        /** Update Player Stats */
        put: operations["update_player_stats_api_v1_matches__match_id__player_stats_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Snapshot */
        get: operations["live_snapshot_api_v1_matches__match_id__live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/competitions/{competition_id}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Standings */
        get: operations["standings_api_v1_competitions__competition_id__standings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/head-to-head/{opponent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Head To Head
         * @description Every finished meeting between two teams, from the first team's side.
         */
        get: operations["head_to_head_api_v1_teams__team_id__head_to_head__opponent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Stats */
        get: operations["player_stats_api_v1_players__player_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stat Leaders
         * @description Rank players by goals, assists, or cards collected, across finished matches.
         */
        get: operations["stat_leaders_api_v1_stats_leaders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/competitions/{competition_id}/awards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Season Awards
         * @description Season honours, drawn from finished matches in one competition.
         */
        get: operations["season_awards_api_v1_competitions__competition_id__awards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign Upload */
        post: operations["presign_upload_api_v1_media_uploads_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminAccountRead */
        AdminAccountRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Player Id */
            player_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            player?: components["schemas"]["PlayerRead"] | null;
            team?: components["schemas"]["TeamRead"] | null;
        };
        /** AdminUserCreate */
        AdminUserCreate: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Invite Code
             * @default unused
             */
            invite_code: string;
            /** @default admin */
            role: components["schemas"]["UserRole"];
        };
        /** AdminUserUpdate */
        AdminUserUpdate: {
            /** Player Id */
            player_id?: string | null;
        };
        /** AuditLogRead */
        AuditLogRead: {
            /** Id */
            id: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Name */
            actor_name: string;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string | null;
            /** Match Id */
            match_id: string | null;
            /** Summary */
            summary: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CompetitionInput */
        CompetitionInput: {
            /** Name */
            name: string;
            /** Season */
            season: string;
            type: components["schemas"]["CompetitionType"];
        };
        /** CompetitionRead */
        CompetitionRead: {
            /** Name */
            name: string;
            /** Season */
            season: string;
            type: components["schemas"]["CompetitionType"];
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CompetitionType
         * @enum {string}
         */
        CompetitionType: "league" | "tournament" | "friendly";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "goal" | "assist" | "own_goal" | "penalty_missed" | "yellow_card" | "red_card" | "substitution";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadToHead */
        HeadToHead: {
            team: components["schemas"]["TeamRead"];
            opponent: components["schemas"]["TeamRead"];
            /** Played */
            played: number;
            /** Won */
            won: number;
            /** Drawn */
            drawn: number;
            /** Lost */
            lost: number;
            /** Goals For */
            goals_for: number;
            /** Goals Against */
            goals_against: number;
            /** Meetings */
            meetings: components["schemas"]["HeadToHeadMeeting"][];
        };
        /** HeadToHeadMeeting */
        HeadToHeadMeeting: {
            /** Match Id */
            match_id: string;
            /**
             * Kickoff Datetime
             * Format: date-time
             */
            kickoff_datetime: string;
            competition?: components["schemas"]["CompetitionRead"] | null;
            home_team?: components["schemas"]["TeamRead"] | null;
            away_team?: components["schemas"]["TeamRead"] | null;
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Result */
            result: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @default aimz-api
             */
            service: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
            /** Environment */
            environment: string;
        };
        /** InviteCreate */
        InviteCreate: {
            /** Label */
            label: string;
            /** Code */
            code: string;
            /** Player Id */
            player_id?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Max Uses */
            max_uses?: number | null;
        };
        /** InviteRead */
        InviteRead: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Player Id */
            player_id: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Max Uses */
            max_uses: number | null;
            /** Use Count */
            use_count: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LineupEntryInput */
        LineupEntryInput: {
            /** Player Id */
            player_id: string;
            /** Team Id */
            team_id: string;
            /**
             * Is Starter
             * @default false
             */
            is_starter: boolean;
            /**
             * Is Captain
             * @default false
             */
            is_captain: boolean;
            /** Position */
            position?: string | null;
            /** Jersey Number */
            jersey_number?: number | null;
        };
        /** LineupEntryRead */
        LineupEntryRead: {
            /** Player Id */
            player_id: string;
            /** Team Id */
            team_id: string;
            /**
             * Is Starter
             * @default false
             */
            is_starter: boolean;
            /**
             * Is Captain
             * @default false
             */
            is_captain: boolean;
            /** Position */
            position?: string | null;
            /** Jersey Number */
            jersey_number?: number | null;
            /** Id */
            id: string;
            /** Match Id */
            match_id: string;
        };
        /** LiveMatchSnapshot */
        LiveMatchSnapshot: {
            match: components["schemas"]["MatchRead"];
            /** Events */
            events: components["schemas"]["MatchEventRead"][];
            /** Lineup */
            lineup: components["schemas"]["LineupEntryRead"][];
            /** Revision */
            revision: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ManOfTheMatchInput */
        ManOfTheMatchInput: {
            /** Player Id */
            player_id?: string | null;
        };
        /** MatchEventInput */
        MatchEventInput: {
            type: components["schemas"]["EventType"];
            /** Minute */
            minute?: number | null;
            /** Team Id */
            team_id: string;
            /** Player Id */
            player_id?: string | null;
            /** Secondary Player Id */
            secondary_player_id?: string | null;
            /** Related Event Id */
            related_event_id?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Is Penalty
             * @default false
             */
            is_penalty: boolean;
            substitution_reason?: components["schemas"]["SubstitutionReason"] | null;
            penalty_outcome?: components["schemas"]["PenaltyOutcome"] | null;
            /** Client Operation Id */
            client_operation_id: string;
        };
        /** MatchEventRead */
        MatchEventRead: {
            type: components["schemas"]["EventType"];
            /** Minute */
            minute?: number | null;
            /** Team Id */
            team_id: string;
            /** Player Id */
            player_id?: string | null;
            /** Secondary Player Id */
            secondary_player_id?: string | null;
            /** Related Event Id */
            related_event_id?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Is Penalty
             * @default false
             */
            is_penalty: boolean;
            substitution_reason?: components["schemas"]["SubstitutionReason"] | null;
            penalty_outcome?: components["schemas"]["PenaltyOutcome"] | null;
            /** Client Operation Id */
            client_operation_id: string;
            /** Id */
            id: string;
            /** Match Id */
            match_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MatchEventUpdate */
        MatchEventUpdate: {
            type?: components["schemas"]["EventType"] | null;
            /** Minute */
            minute?: number | null;
            /** Team Id */
            team_id?: string | null;
            /** Player Id */
            player_id?: string | null;
            /** Secondary Player Id */
            secondary_player_id?: string | null;
            /** Notes */
            notes?: string | null;
            /** Is Penalty */
            is_penalty?: boolean | null;
            substitution_reason?: components["schemas"]["SubstitutionReason"] | null;
            penalty_outcome?: components["schemas"]["PenaltyOutcome"] | null;
        };
        /** MatchInput */
        MatchInput: {
            /** Competition Id */
            competition_id: string;
            /** Home Team Id */
            home_team_id: string;
            /** Away Team Id */
            away_team_id: string;
            /**
             * Kickoff Datetime
             * Format: date-time
             */
            kickoff_datetime: string;
            /** Venue */
            venue: string;
            /** @default scheduled */
            status: components["schemas"]["MatchStatus"];
            /**
             * Half Length Minutes
             * @default 45
             */
            half_length_minutes: number;
            /**
             * Num Halves
             * @default 2
             */
            num_halves: number;
            /**
             * Half Time Break Minutes
             * @default 15
             */
            half_time_break_minutes: number;
            /**
             * Has Extra Time
             * @default false
             */
            has_extra_time: boolean;
            /**
             * Extra Time Half Length Minutes
             * @default 15
             */
            extra_time_half_length_minutes: number;
            /** Lineup Format */
            lineup_format?: number | null;
            /** Formation */
            formation?: string | null;
        };
        /**
         * MatchPhase
         * @enum {string}
         */
        MatchPhase: "not_started" | "first_half" | "halftime" | "second_half" | "extra_time" | "finished";
        /** MatchPhaseUpdate */
        MatchPhaseUpdate: {
            /**
             * Action
             * @enum {string}
             */
            action: "start_match" | "halftime" | "start_second_half" | "start_extra_time" | "finish_match";
        };
        /** MatchRead */
        MatchRead: {
            /** Competition Id */
            competition_id: string;
            /** Home Team Id */
            home_team_id: string;
            /** Away Team Id */
            away_team_id: string;
            /**
             * Kickoff Datetime
             * Format: date-time
             */
            kickoff_datetime: string;
            /** Venue */
            venue: string;
            /** @default scheduled */
            status: components["schemas"]["MatchStatus"];
            /**
             * Half Length Minutes
             * @default 45
             */
            half_length_minutes: number;
            /**
             * Num Halves
             * @default 2
             */
            num_halves: number;
            /**
             * Half Time Break Minutes
             * @default 15
             */
            half_time_break_minutes: number;
            /**
             * Has Extra Time
             * @default false
             */
            has_extra_time: boolean;
            /**
             * Extra Time Half Length Minutes
             * @default 15
             */
            extra_time_half_length_minutes: number;
            /** Lineup Format */
            lineup_format?: number | null;
            /** Formation */
            formation?: string | null;
            /** Id */
            id: string;
            phase: components["schemas"]["MatchPhase"];
            /** Man Of The Match Player Id */
            man_of_the_match_player_id?: string | null;
            /** Phase Started At */
            phase_started_at: string | null;
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Revision */
            revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            home_team?: components["schemas"]["TeamRead"] | null;
            away_team?: components["schemas"]["TeamRead"] | null;
            competition?: components["schemas"]["CompetitionRead"] | null;
        };
        /**
         * MatchResultInput
         * @description The final score of a match nobody from AIMZ was at to score live.
         */
        MatchResultInput: {
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
        };
        /**
         * MatchStatus
         * @enum {string}
         */
        MatchStatus: "scheduled" | "live" | "finished";
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** Page[AdminAccountRead] */
        Page_AdminAccountRead_: {
            /** Items */
            items: components["schemas"]["AdminAccountRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[AuditLogRead] */
        Page_AuditLogRead_: {
            /** Items */
            items: components["schemas"]["AuditLogRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[CompetitionRead] */
        Page_CompetitionRead_: {
            /** Items */
            items: components["schemas"]["CompetitionRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[MatchRead] */
        Page_MatchRead_: {
            /** Items */
            items: components["schemas"]["MatchRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[PlayerRead] */
        Page_PlayerRead_: {
            /** Items */
            items: components["schemas"]["PlayerRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[TeamRead] */
        Page_TeamRead_: {
            /** Items */
            items: components["schemas"]["TeamRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Code */
            code: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * PenaltyOutcome
         * @enum {string}
         */
        PenaltyOutcome: "saved" | "off_target";
        /** PlayerAward */
        PlayerAward: {
            /** Label */
            label: string;
            player: components["schemas"]["PlayerRead"];
            team: components["schemas"]["TeamRead"];
            /** Value */
            value: number;
            /** Unit */
            unit: string;
        };
        /** PlayerInput */
        PlayerInput: {
            /** Name */
            name: string;
            /** Team Id */
            team_id: string;
            /** Position */
            position: string;
            /** Jersey Number */
            jersey_number?: number | null;
            /** Photo Key */
            photo_key?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** PlayerLeaderRow */
        PlayerLeaderRow: {
            /** Rank */
            rank: number;
            player: components["schemas"]["PlayerRead"];
            team: components["schemas"]["TeamRead"];
            /** Goals */
            goals: number;
            /** Assists */
            assists: number;
            /** Yellow Cards */
            yellow_cards: number;
            /** Red Cards */
            red_cards: number;
            /** Appearances */
            appearances: number;
        };
        /** PlayerMatchStatRead */
        PlayerMatchStatRead: {
            /** Player Id */
            player_id: string;
            /** Appeared */
            appeared: boolean;
            /** Minutes Played */
            minutes_played: number;
            /** Id */
            id: string;
            /** Match Id */
            match_id: string;
            /** Goals */
            goals: number;
            /** Assists */
            assists: number;
            /** Own Goals */
            own_goals: number;
            /** Yellow Cards */
            yellow_cards: number;
            /** Red Cards */
            red_cards: number;
        };
        /** PlayerRead */
        PlayerRead: {
            /** Name */
            name: string;
            /** Team Id */
            team_id: string;
            /** Position */
            position: string;
            /** Jersey Number */
            jersey_number?: number | null;
            /** Photo Key */
            photo_key?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Photo Url */
            photo_url?: string | null;
        };
        /** PlayerSeasonSummary */
        PlayerSeasonSummary: {
            player: components["schemas"]["PlayerRead"];
            /** Season */
            season: string | null;
            /** Appearances */
            appearances: number;
            /** Minutes Played */
            minutes_played: number;
            /** Goals */
            goals: number;
            /** Assists */
            assists: number;
            /** Own Goals */
            own_goals: number;
            /** Yellow Cards */
            yellow_cards: number;
            /** Red Cards */
            red_cards: number;
            /** Matches */
            matches: components["schemas"]["PlayerMatchStatRead"][];
        };
        /** PlayerStatInput */
        PlayerStatInput: {
            /** Player Id */
            player_id: string;
            /** Appeared */
            appeared: boolean;
            /** Minutes Played */
            minutes_played: number;
        };
        /** PresignRequest */
        PresignRequest: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "team" | "player";
            /** Entity Id */
            entity_id: string;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp";
        };
        /** PresignResponse */
        PresignResponse: {
            /** Upload Url */
            upload_url: string;
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Object Key */
            object_key: string;
            /** Expires In */
            expires_in: number;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "connected" | "unavailable";
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Invite Code */
            invite_code: string;
        };
        /** SeasonAwards */
        SeasonAwards: {
            competition: components["schemas"]["CompetitionRead"];
            /** Player Awards */
            player_awards?: components["schemas"]["PlayerAward"][];
            /** Team Awards */
            team_awards?: components["schemas"]["TeamAward"][];
        };
        /** StandingRow */
        StandingRow: {
            /** Rank */
            rank: number;
            team: components["schemas"]["TeamRead"];
            /** Form */
            form?: string[];
            /** Played */
            played: number;
            /** Won */
            won: number;
            /** Drawn */
            drawn: number;
            /** Lost */
            lost: number;
            /** Goals For */
            goals_for: number;
            /** Goals Against */
            goals_against: number;
            /** Goal Difference */
            goal_difference: number;
            /** Points */
            points: number;
        };
        /**
         * SubstitutionReason
         * @enum {string}
         */
        SubstitutionReason: "tactical" | "injury" | "concussion" | "disciplinary" | "other";
        /** TeamAward */
        TeamAward: {
            /** Label */
            label: string;
            team: components["schemas"]["TeamRead"];
            /** Value */
            value: number;
            /** Unit */
            unit: string;
        };
        /** TeamInput */
        TeamInput: {
            /** Name */
            name: string;
            /** Squad Code */
            squad_code?: string | null;
            /** Age Group */
            age_group?: string | null;
            /** Season */
            season?: string | null;
            /**
             * Is Aimz
             * @default false
             */
            is_aimz: boolean;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Logo Key */
            logo_key?: string | null;
            /** Coach */
            coach?: string | null;
            /** Assistant Coach */
            assistant_coach?: string | null;
            /** Competition Id */
            competition_id?: string | null;
        };
        /** TeamRead */
        TeamRead: {
            /** Name */
            name: string;
            /** Squad Code */
            squad_code?: string | null;
            /** Age Group */
            age_group?: string | null;
            /** Season */
            season?: string | null;
            /**
             * Is Aimz
             * @default false
             */
            is_aimz: boolean;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Logo Key */
            logo_key?: string | null;
            /** Coach */
            coach?: string | null;
            /** Assistant Coach */
            assistant_coach?: string | null;
            /** Competition Id */
            competition_id?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Logo Url */
            logo_url?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserRead"];
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Player Id */
            player_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "player" | "admin";
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_password_reset_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_password_reset_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    delete_me_api_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_log_api_v1_admin_audit_log_get: {
        parameters: {
            query?: {
                match_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditLogRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AdminAccountRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_user_player_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_api_v1_admin_registration_invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteRead"][];
                };
            };
        };
    };
    create_invite_api_v1_admin_registration_invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_api_v1_admin_registration_invites__invite_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_v1_teams_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                is_aimz?: boolean | null;
                season?: string | null;
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TeamRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_team_api_v1_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_api_v1_teams__team_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_api_v1_teams__team_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_competitions_api_v1_competitions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                season?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CompetitionRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_competition_api_v1_competitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_competition_api_v1_competitions__competition_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_competition_api_v1_competitions__competition_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_api_v1_players_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                team_id?: string | null;
                season?: string | null;
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PlayerRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_player_api_v1_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_api_v1_players__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_api_v1_players__player_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_v1_matches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                match_status?: components["schemas"]["MatchStatus"] | null;
                team_id?: string | null;
                competition_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MatchRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_api_v1_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_match_api_v1_matches__match_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_api_v1_matches__match_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_phase_api_v1_matches__match_id__phase_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchPhaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_result_api_v1_matches__match_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchResultInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_man_of_the_match_api_v1_matches__match_id__man_of_the_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManOfTheMatchInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_matches__match_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_v1_matches__match_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchEventInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchEventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_api_v1_matches__match_id__events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_event_api_v1_matches__match_id__events__event_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchEventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchEventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineup_api_v1_matches__match_id__lineup_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineupEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_lineup_api_v1_matches__match_id__lineup_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineupEntryInput"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineupEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_stats_api_v1_matches__match_id__player_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerMatchStatRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_stats_api_v1_matches__match_id__player_stats_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerStatInput"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerMatchStatRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_snapshot_api_v1_matches__match_id__live_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveMatchSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    standings_api_v1_competitions__competition_id__standings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_to_head_api_v1_teams__team_id__head_to_head__opponent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
                opponent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeadToHead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_stats_api_v1_players__player_id__stats_get: {
        parameters: {
            query?: {
                season?: string | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSeasonSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stat_leaders_api_v1_stats_leaders_get: {
        parameters: {
            query?: {
                metric?: "goals" | "assists" | "cards";
                age_group?: string | null;
                season?: string | null;
                competition_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerLeaderRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    season_awards_api_v1_competitions__competition_id__awards_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonAwards"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_upload_api_v1_media_uploads_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
