import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

import { theme } from '@/src/theme';

type Option = { label: string; value: string };

export function ChoiceField({ label, value, options, onChange, placeholder = 'Choose one', error }: { label: string; value?: string; options: Option[]; onChange: (value: string) => void; placeholder?: string; error?: string }) {
  const [open, setOpen] = useState(false);
  const selected = options.find((item) => item.value === value);
  return <View style={styles.group}><Text style={styles.label}>{label}</Text><Pressable accessibilityLabel={label} accessibilityRole="button" onPress={() => setOpen(true)} style={({ pressed }) => [styles.field, error && styles.fieldError, pressed && styles.pressed]}><Text style={[styles.value, !selected && styles.placeholder]}>{selected?.label ?? placeholder}</Text><Ionicons color={theme.colors.textMuted} name="chevron-down" size={20} /></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}<Modal animationType="slide" onRequestClose={() => setOpen(false)} presentationStyle="pageSheet" visible={open}><SafeAreaView style={styles.modal}><View style={styles.modalHeader}><Text accessibilityRole="header" style={styles.title}>{label}</Text><Pressable accessibilityLabel="Close choices" accessibilityRole="button" onPress={() => setOpen(false)} style={styles.close}><Ionicons color={theme.colors.textPrimary} name="close" size={24} /></Pressable></View><ScrollView contentContainerStyle={styles.options}>{options.map((option) => <Pressable key={option.value} onPress={() => { onChange(option.value); setOpen(false); }} style={({ pressed }) => [styles.option, option.value === value && styles.optionSelected, pressed && styles.pressed]}><Text style={styles.optionText}>{option.label}</Text>{option.value === value ? <Ionicons color={theme.colors.lightBlue} name="checkmark" size={22} /> : null}</Pressable>)}</ScrollView></SafeAreaView></Modal></View>;
}

const styles = StyleSheet.create({ group: { gap: theme.spacing.xs }, label: { color: theme.colors.textSecondary, fontSize: theme.type.label, fontWeight: '700' }, field: { alignItems: 'center', backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radius.md, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 52, paddingHorizontal: theme.spacing.md }, fieldError: { borderColor: theme.colors.error }, value: { color: theme.colors.textPrimary, flex: 1, fontSize: theme.type.body }, placeholder: { color: theme.colors.textMuted }, error: { color: theme.colors.errorText, fontSize: theme.type.caption }, pressed: { opacity: 0.7 }, modal: { backgroundColor: theme.colors.background, flex: 1 }, modalHeader: { alignItems: 'center', borderBottomColor: theme.colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: theme.spacing.lg }, title: { color: theme.colors.textPrimary, fontSize: theme.type.heading, fontWeight: '900' }, close: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 }, options: { gap: theme.spacing.sm, padding: theme.spacing.lg }, option: { alignItems: 'center', backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radius.md, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 56, padding: theme.spacing.md }, optionSelected: { borderColor: theme.colors.accent }, optionText: { color: theme.colors.textPrimary, fontWeight: '700' } });
