export const palette = {
  navy: '#16225A',
  deepNavy: '#0F1A45',
  accentBlue: '#3D9BE9',
  lightBlue: '#6FC5F0',
  white: '#FFFFFF',
  magenta: '#E1306C',
  orange: '#F77737',
  yellow: '#FCAF45',
  green: '#22C55E',
  amber: '#F59E0B',
  red: '#EF4444',
} as const;

export const theme = {
  colors: {
    background: '#09112F',
    surface: palette.deepNavy,
    surfaceRaised: palette.navy,
    border: '#2C3A78',
    accent: palette.accentBlue,
    lightBlue: palette.lightBlue,
    onAccent: '#07132F',
    textPrimary: palette.white,
    textSecondary: '#C9D4F2',
    textMuted: '#97A6D1',
    live: palette.green,
    liveSurface: '#123E38',
    liveText: '#86EFAC',
    warning: palette.amber,
    warningSurface: '#3A2A0C',
    warningText: '#FCD34D',
    error: palette.red,
    errorSurface: '#5A1C2D',
    errorText: '#FCA5A5',
    progressTrack: '#24305F',
    highlightedSurface: '#152C5F',
  },
  gradient: [palette.magenta, palette.orange, palette.yellow] as const,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    xxxl: 64,
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 20,
    pill: 999,
  },
  type: {
    caption: 12,
    label: 14,
    body: 16,
    heading: 22,
    display: 30,
    score: 36,
  },
  touch: {
    minimum: 44,
  },
  motion: {
    quick: 160,
    standard: 240,
  },
} as const;

export type Theme = typeof theme;
