import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { useAuth } from '@/src/auth/AuthProvider';
import { AppButton } from '@/src/components/AppButton';
import { MatchProgressRail, MatchStatusIndicator } from '@/src/components/MatchStatusIndicator';
import { Screen } from '@/src/components/Screen';
import { ErrorState, LoadingState } from '@/src/components/StateView';
import { api, ApiError } from '@/src/lib/api';
import { useMatchClock } from '@/src/lib/matchClock';
import { theme } from '@/src/theme';

const eventLabel = { goal: 'Goal', assist: 'Assist', yellow_card: 'Yellow card', red_card: 'Red card', substitution: 'Substitution' } as const;

export default function MatchDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { user } = useAuth();
  const query = useQuery({ queryKey: ['live-match', id], queryFn: () => api.live(id), enabled: Boolean(id), refetchInterval: (state) => state.state.data?.match.status === 'finished' ? false : 12_000 });
  const players = useQuery({ queryKey: ['players'], queryFn: () => api.players('?limit=100') });
  const playerNames = new Map(players.data?.items.map((player) => [player.id, player.name]));
  const clock = useMatchClock(query.data?.match);
  return <Screen action={<Pressable accessibilityLabel="Go back" accessibilityRole="button" hitSlop={10} onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><Ionicons color={theme.colors.textPrimary} name="chevron-back" size={24} /></Pressable>} eyebrow="Match detail" title="Game centre">
    {query.isLoading ? <LoadingState label="Loading match" /> : query.isError || !query.data ? <ErrorState message={(query.error as ApiError)?.message ?? 'Match not found.'} onRetry={() => query.refetch()} /> : <>
      <View style={styles.hero}><View style={styles.statusRow}><MatchStatusIndicator clock={clock} muted={query.data.match.status !== 'live'} /><Text style={styles.competition}>{query.data.match.competition?.name}</Text></View><View style={styles.scoreRow}><View style={styles.team}><Text style={styles.teamName}>{query.data.match.home_team?.name}</Text></View><Text accessibilityLabel={`${query.data.match.home_score} to ${query.data.match.away_score}`} style={styles.score}>{query.data.match.home_score}–{query.data.match.away_score}</Text><View style={[styles.team, styles.away]}><Text style={[styles.teamName, styles.alignRight]}>{query.data.match.away_team?.name}</Text></View></View><Text style={styles.meta}>{new Intl.DateTimeFormat('en-EG', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(query.data.match.kickoff_datetime))} · {query.data.match.venue}</Text>{query.data.match.status === 'live' ? <MatchProgressRail clock={clock} /> : null}{user?.role === 'admin' ? <AppButton label={query.data.match.status === 'scheduled' ? 'Open match management' : 'Open live scoring'} onPress={() => router.push(`/live/${id}`)} /> : null}</View>
      <View style={styles.section}><Text style={styles.sectionTitle}>Timeline</Text>{query.data.events.length === 0 ? <Text style={styles.empty}>Match events will appear here.</Text> : query.data.events.map((event) => <View key={event.id} style={styles.event}><View style={styles.eventIcon}><Ionicons color={event.type === 'red_card' ? theme.colors.error : event.type === 'yellow_card' ? theme.colors.warning : theme.colors.lightBlue} name={event.type === 'substitution' ? 'swap-horizontal' : event.type.includes('card') ? 'square' : 'football'} size={18} /></View><View style={styles.eventCopy}><Text style={styles.eventTitle}>{eventLabel[event.type]}</Text><Text style={styles.eventPlayer}>{event.player_id ? playerNames.get(event.player_id) ?? 'Player' : query.data.match.home_team_id === event.team_id ? query.data.match.home_team?.name : query.data.match.away_team?.name}</Text></View><Text style={styles.minute}>{event.minute == null ? 'FT' : `${event.minute}'`}</Text></View>)}</View>
      <View style={styles.section}><Text style={styles.sectionTitle}>Lineups</Text>{query.data.lineup.length === 0 ? <Text style={styles.empty}>No lineup has been entered.</Text> : query.data.lineup.map((entry) => <View key={entry.id} style={styles.lineup}><Text style={styles.lineupName}>{playerNames.get(entry.player_id) ?? 'Player'}</Text><Text style={styles.lineupMeta}>{entry.is_starter ? 'Starter' : 'Substitute'} · {entry.position ?? 'Position not set'}</Text></View>)}</View>
    </>}
  </Screen>;
}
const styles = StyleSheet.create({ back: { alignItems: 'center', backgroundColor: theme.colors.surface, borderRadius: 22, height: 44, justifyContent: 'center', width: 44 }, pressed: { opacity: 0.7 }, hero: { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radius.lg, borderWidth: 1, gap: theme.spacing.lg, padding: theme.spacing.lg }, statusRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, competition: { color: theme.colors.textSecondary, fontSize: theme.type.caption }, scoreRow: { alignItems: 'center', flexDirection: 'row' }, team: { flex: 1 }, away: { alignItems: 'flex-end' }, teamName: { color: theme.colors.textPrimary, fontSize: theme.type.body, fontWeight: '800' }, alignRight: { textAlign: 'right' }, score: { color: theme.colors.textPrimary, fontSize: 48, fontVariant: ['tabular-nums'], fontWeight: '900', letterSpacing: -2, marginHorizontal: theme.spacing.md }, meta: { color: theme.colors.textMuted, textAlign: 'center' }, section: { gap: theme.spacing.sm }, sectionTitle: { color: theme.colors.textPrimary, fontSize: theme.type.heading, fontWeight: '900' }, empty: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, color: theme.colors.textMuted, padding: theme.spacing.lg, textAlign: 'center' }, event: { alignItems: 'center', backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radius.md, borderWidth: 1, flexDirection: 'row', gap: theme.spacing.md, minHeight: 64, padding: theme.spacing.md }, eventIcon: { alignItems: 'center', backgroundColor: theme.colors.surfaceRaised, borderRadius: 20, height: 40, justifyContent: 'center', width: 40 }, eventCopy: { flex: 1 }, eventTitle: { color: theme.colors.textPrimary, fontWeight: '800' }, eventPlayer: { color: theme.colors.textMuted, marginTop: 2 }, minute: { color: theme.colors.lightBlue, fontVariant: ['tabular-nums'], fontWeight: '900' }, lineup: { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radius.md, borderWidth: 1, padding: theme.spacing.md }, lineupName: { color: theme.colors.textPrimary, fontWeight: '800' }, lineupMeta: { color: theme.colors.textMuted, marginTop: 3 } });
