/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 380736d536ec47428d14ccfe719346d9)
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: "staging";
	FRONTEND_ORIGIN: "https://aimz-egypt-staging.pages.dev";
	ADMIN_NAME: "AIMZ Staging Admin";
	ACCESS_TOKEN_SECONDS: "900";
	REFRESH_TOKEN_DAYS: "30";
	JWT_SECRET: string;
	ADMIN_EMAIL: string;
	ADMIN_PASSWORD: string;
	INITIAL_INVITE_CODE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "FRONTEND_ORIGIN" | "ADMIN_NAME" | "ACCESS_TOKEN_SECONDS" | "REFRESH_TOKEN_DAYS" | "JWT_SECRET" | "ADMIN_EMAIL" | "ADMIN_PASSWORD" | "INITIAL_INVITE_CODE">> {}
}
