/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cfd920e83ae908804ad4f21322b9a005)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: "staging";
	FRONTEND_ORIGIN: "https://aimz-egypt-staging.pages.dev";
	PUBLIC_FORM_ORIGIN: "https://aimzegypt-73b85.web.app";
	TURNSTILE_HOSTNAMES: "aimzegypt-73b85.web.app";
	ADMIN_NAME: "AIMZ Staging Admin";
	ACCESS_TOKEN_SECONDS: "900";
	REFRESH_TOKEN_DAYS: "30";
	MEDIA_MAX_BYTES: "5242880";
	JWT_SECRET: string;
	ADMIN_EMAIL: string;
	ADMIN_PASSWORD: string;
	INITIAL_INVITE_CODE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "FRONTEND_ORIGIN" | "PUBLIC_FORM_ORIGIN" | "TURNSTILE_HOSTNAMES" | "ADMIN_NAME" | "ACCESS_TOKEN_SECONDS" | "REFRESH_TOKEN_DAYS" | "MEDIA_MAX_BYTES" | "JWT_SECRET" | "ADMIN_EMAIL" | "ADMIN_PASSWORD" | "INITIAL_INVITE_CODE">> {}
}
